### PR TITLE
Android bindings dockerization

### LINKED ISSUE #5: Fix Android integration
After updating android integration in this project, trying run `./gradlew build` I've encountered this error:
```
   Compiling lnpbp v0.1.0-rc.1 (https://github.com/LNP-BP/rust-lnpbp?branch=master#7b7284a4)
error: /mnt/dmc/zoe/work/LNP-BP/rgb-sdk/rust-lib/target/debug/deps/libamplify_derive-3530b0645a331e12.so: undefined symbol: __errno
  --> /home/zoe/.cargo/git/checkouts/rust-lnpbp-1c6b6ac6d4fb658b/7b7284a/src/lib.rs:36:1
   |
36 | extern crate amplify_derive;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `lnpbp`
```
After a `cargo clean` the same error can appear for `lnpbp_derive`. Both dependencies are `proc-macro` and are lnp-bp forks.
The symbol `__errno` is defined in `libc.so` but in `libamplify_derive_xxx.so` and `liblnpbp_derive_xxx.so` the symbol is actually undefined and unlinked (inspected with `nm`). Same error happens when building from `rgb-node` `v0.1.0-rc.1`.

To avoid mixing possible project update errors (since integrations have been moved to separate project, there's the possibility I forgot/mistaken to update some paths/commands), I re-added android integration on `rgb-node` `master` (as it was before removing it, see [this branch](https://github.com/zoedberg/rgb-node/tree/ffi_android)) and I receive a different error:
```
    Updating git repository `https://github.com/LNP-BP/rust-lnpbp`
error: failed to select a version for `secp256k1-sys`.
    ... required by package `secp256k1 v0.18.0`
    ... which is depended on by `bitcoin v0.24.0`
    ... which is depended on by `miniscript v2.0.0`
    ... which is depended on by `lnpbp v0.1.0-rc.2 (https://github.com/LNP-BP/rust-lnpbp?branch=master#82e56fb0)`
    ... which is depended on by `rgb_node v0.1.0-rc.2 (/mnt/dmc/zoe/work/LNP-BP/rgb-node)`
    ... which is depended on by `rgb v0.1.0-rc.1 (/mnt/dmc/zoe/work/LNP-BP/rgb-node/ffi)`
versions that meet the requirements `^0.2.0` are: 0.2.0

the package `secp256k1-sys` links to the native library `rustsecp256k1_v0_2_0`, but it conflicts with a previous package which links to `rustsecp256k1_v0_2_0` as well:
package `secp256k1-sys v0.3.0`
    ... which is depended on by `secp256k1 v0.19.0`
    ... which is depended on by `bitcoin v0.25.0`
    ... which is depended on by `electrum-client v0.3.0-beta.1`
    ... which is depended on by `rgb_node v0.1.0-rc.2 (/mnt/dmc/zoe/work/LNP-BP/rgb-node)`
    ... which is depended on by `rgb v0.1.0-rc.1 (/mnt/dmc/zoe/work/LNP-BP/rgb-node/ffi)`

failed to select a version for `secp256k1-sys` which could resolve this conflict
```

Which is pretty strange since `miniscript v2.0.0` (commit `ba436de`) has defined `bitcoin v0.25.0` (tag `lnpbp-v0.1.0-rc1`) in its `Cargo.toml`, not `v0.24.0` as the error message reports.

I've tried to cross-compile `rust-lnpbp`, since it seems to be the package that's causing these problems, and it returns the first error I've reported (`undefined symbol: __errno` on `(lnpbp|amplify)_derive`).

On `rgb-sdk`, in `ffi/android/build_rust.sh`, I've added a `cargo build` (without `--target`, so amd64) on top of the file. That causes the android build to succeed. But then, when loading the `library-debug.aar` on the android react native demo I receive this error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.react_native_demo, PID: 30090
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZNSt6__ndk15ctypeIcE2idE" referenced by "/data/app/com.react_native_demo-xe4-dVhYDMVR1llkVN4klg==/lib/x86/librgb.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.react_native_demo.MainApplication.onCreate(MainApplication.java:57)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
That's strange too, since that symbol should be in `libc++_shared.so`.
In order to verify this, I've done the following:
```
$ANDROID_SDK_ROOT/platform-tools/adb pull "/data/app/com.react_native_demo-xe4-dVhYDMVR1llkVN4klg==/lib/x86/librgb.so" "/home/zoe/work/LNP-BP/librgb_node.so"
$ANDROID_SDK_ROOT/platform-tools/adb pull "/data/app/com.react_native_demo-xe4-dVhYDMVR1llkVN4klg==/lib/x86/libc++_shared.so" "/home/zoe/work/LNP-BP/libc++_shared.so"

$NDK_HOME/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-objdump -T ~/work/LNP-BP/librgb.so | less

# piece of output:
00000000      D  *UND*  00000000              _ZNSt6__ndk15ctypeIcE2idE
# it's actually undefined, and unfortunately unlinked

$NDK_HOME/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-objdump -T ~/work/LNP-BP/libc++_shared.so | less

# piece of output:
000e6fb0 g    DO .bss   00000008  Base        _ZNSt6__ndk15ctypeIcE2idE
# it's defined
```

I've added a Dockerfile that may help debugging the situation, both in [`rgb-sdk`](https://github.com/zoedberg/rgb-sdk/tree/fix_android) and in [`rgb-node`](https://github.com/zoedberg/rgb-node/tree/ffi_android).
On `rgb-node` the behavior is consistent with the local one (fail caused by `secp256k1-sys`).
On `rgb-sdk` the behavior is inconsistent with the local one, the build is still successful, but the package doesn't contain the `jni` directory with the `*.so` files:
```
unzip -l library-debug.aar
Archive:  library-debug.aar
  Length      Date    Time    Name
---------  ---------- -----   ----
    88185  1980-02-01 00:00   R.txt
      303  1980-02-01 00:00   AndroidManifest.xml
    12663  1980-02-01 00:00   classes.jar
---------                     -------
   101151                     3 files

```
This actually happened to me also locally, but I haven't determined what causes and fixes that yet.

### LINKED ISSUE #8: Post-release check for v0.1.0
Today I made a final release of version 0.1 for both LNP/BP Core Library and RGB Node crates + updated corresponding docker images. We need to move to crate links in this repo and make sure everything builds and create a release here as well. As the last-minute change there was a removal of the need to provide fee size for the RGB Node in transfer request (it is now auto-computed from PSBT data), so we need to make sure that have not broke anything here.

Local changes needed:
- In https://github.com/LNP-BP/rgb-sdk/blob/master/rust-lib/Cargo.toml
    * Remove all crates from `[patch.crates-io]` section, **leave only** `zeromq-src`
    * Change RGB Node dependency on "~0.1.0" (from github path). Current master should not build here (it already have diverged and moved on work on v0.2 with Lightning)
- Change all GitHub RGB Node downloads in Dockerfile are happening from `v0.1.0` tag

Once everything work I will do a crate release for Rust bindings, and probably later we will work on NPM module release as well

### PR DESCRIPTION
**Pull request by zoedberg**

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,14 +1,32 @@
 # Generated by Cargo
 # will have compiled files and executables
-target/
-builds/
+/rust-lib/target
```
Comment (dr-orlovsky) [inline .gitignore]: I prefer to have generic `target/` exclusion: it allows to get rid if this directory when you get multiple crates in the same repo

File: ffi/android/Dockerfile [hunk 2]
```diff
@@ -0,0 +1,60 @@
+FROM rustlang/rust:nightly-slim as builder
```
Comment (dr-orlovsky) [inline ffi/android/Dockerfile]: BTW, can we stick to a specific nightly version here? We had experience of nightly versions breaking before

File: ffi/android/Dockerfile [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+RUN wget https://freefr.dl.sourceforge.net/project/swig/swig/swig-4.0.1/swig-4.0.1.tar.gz && \
+    tar xf swig-*.tar.gz && \
+    cd swig-* && \
+    ./configure && make -j12 && \
+    make install && \
+    rm -rf /tmp/*
+
+ENV ANDROID_SDK_ROOT=/root/sdk
+ENV NDK_VERSION=20.1.5948944
+ENV NDK_HOME=$ANDROID_SDK_ROOT/ndk/$NDK_VERSION
```
Comment (dr-orlovsky) [inline ffi/android/Dockerfile]: Maybe better make them `ARG`s?

File: ffi/android/Dockerfile [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+linker = "/root/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"\n\n\
+[target.x86_64-linux-android]\n\
+ar = "/root/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android-ar"\n\
+linker = "/root/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang"\n\n\
+[target.armv7-linux-androideabi]\n\
+ar = "/root/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar"\n\
+linker = "/root/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi26-clang"\n\n\
+[target.i686-linux-android]\n\
+ar = "/root/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-ar"\n\
+linker = "/root/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android26-clang"' > $CARGO_HOME/config.toml
```
Comment (dr-orlovsky) [inline ffi/android/Dockerfile]: May be better to create a file with this settings and later just copy it?

File: ffi/android/Dockerfile [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+        x86_64-linux-android \
+        armv7-linux-androideabi \
+        i686-linux-android
+
+COPY ffi/android /rgb-sdk/ffi/android
+COPY rust-lib /rgb-sdk/rust-lib
+
+WORKDIR /rgb-sdk/ffi/android
+
+RUN ./gradlew build
```
Comment (dr-orlovsky) [inline ffi/android/Dockerfile:47]: Not sure I understand where the compiled library is stored. Neither README do not help with that

**Review by dr-orlovsky — COMMENTED** [review]
Few questions and some nits

File: ffi/android/Dockerfile (hunk 5 above)
Comment (zoedberg) [reply ffi/android/Dockerfile:47]: from README:
> Both instructions will generate the artifacts (library-debug.aar and library-release.aar) in ffi/android/library/build/outputs/aar/.

is the README unclear or did you miss this phrase?

File: .gitignore (hunk 1 above)
Comment (zoedberg) [reply .gitignore]: changed in `**/target` (for git is the same as `target/`), but in `.dockerignore` it's necessary to make it explicit that you want a recursive search. so to keep the 2 files alligned I've used their common syntax

File: ffi/android/Dockerfile (hunk 2 above)
Comment (zoedberg) [reply ffi/android/Dockerfile]: [rustlang/rust](https://hub.docker.com/r/rustlang/rust/) does not keep track of specific versions, it just uses `nightly` and `nightly-slim` and overrides them over time.

[rust](https://hub.docker.com/_/rust), which should be better since it contains the official docker images for rust, unfortunately does not have the latest releases.

for this project we should need to use `rust:1.49-slim-buster` but the latest available tag is `1.47-slim-buster` (which is too old for this project, it gives `E0554` at build time). so we can open an issue and do it as soon as they publish an updated image.

File: ffi/android/Dockerfile (hunk 3 above)
Comment (zoedberg) [reply ffi/android/Dockerfile]: `NDK_VERSION` can be an `ARG`, but `ANDROID_SDK_ROOT` and `NDK_HOME` are more useful as env variables, since one could launch the image to debug the bindings from inside a container, and those variables are needed for build

File: ffi/android/Dockerfile (hunk 2 above)
Comment (dr-orlovsky) [reply ffi/android/Dockerfile]: Fortunately this night I was able to make both LNP/BP Core Lib and RGB Node compiling on rust down to 1.41.1, so we can switch to normal versions like I did here https://github.com/LNP-BP/docker/commit/0aad29ed364169a1d8502e2139930eb3a5fbb3fb#diff-d4c727902165b154b499e32ea11043fbf11b2b5e9c285a1d2f2be3863f5363a6 and here https://github.com/LNP-BP/rgb-node/commit/4502981bbf3ce1538fb6fc8acf82cadbd2c5ef16

File: ffi/android/Dockerfile (hunk 3 above)
Comment (dr-orlovsky) [reply ffi/android/Dockerfile]: Good, can we do that?

File: ffi/android/Dockerfile (hunk 5 above)
Comment (dr-orlovsky) [reply ffi/android/Dockerfile:47]: I have missed it though I was looking for it. Nevermind, I just have to sleep more

File: ffi/android/Dockerfile (hunk 4 above)
Comment (zoedberg) [reply ffi/android/Dockerfile]: from [here](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure) I understand that this config could be kept in the project. so I was about to propose to add it to the project in `ffi/android/.cargo/config.toml` and document on the local instructions to just update that file with the correct path to their `NDK_HOME`. but that solution wasn't really nice, since users, after changing the file with their paths, would always find the git working directory dirty

so reading documentation I've discovered 2 things:
- `ar` is deprecated, as documented [here](https://doc.rust-lang.org/cargo/reference/config.html#target) (I've tested it and I can confirm that it successfully builds without it)
- we can use configuration environment variables instead of cargo's config (documented [here](https://doc.rust-lang.org/cargo/reference/environment-variables.html#configuration-environment-variables))

this last solution is my preferred, I've added a commit with it so you can review it and tell me what do you think about it

File: ffi/android/Dockerfile (hunk 3 above)
Comment (zoedberg) [reply ffi/android/Dockerfile]: yep, done

File: ffi/android/Dockerfile (hunk 5 above)
Comment (zoedberg) [reply ffi/android/Dockerfile:47]: no problem ;)

File: ffi/android/build_rust.sh [hunk 6]
```diff
@@ -8,6 +8,11 @@ cargo build --manifest-path $RUSTLIB/Cargo.toml
 # Update this line accordingly if you are not building *from* x86_64
 export PATH=$PATH:$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
 
+export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"
+export CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android26-clang"
+export CARGO_TARGET_ARMV7_LINUX_ANDROIDEABI_LINKER="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi26-clang"
+export CARGO_TARGET_I686_LINUX_ANDROID_LINKER="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android26-clang"
+
```
Comment (dr-orlovsky) [inline ffi/android/build_rust.sh:15]: This looks good. Another idea for docker build: we can use `.env` file with all these paths. If it stored in the same directory as docker-compose docker will automatically apply those env vars. We will need docker-compose for that, but I think that's not problematic

File: ffi/android/Dockerfile [hunk 7]
```diff
@@ -0,0 +1,47 @@
+FROM rustlang/rust:nightly-slim
```
Comment (dr-orlovsky) [inline ffi/android/Dockerfile]:
```suggestion
FROM rust:1.47.0-slim-buster
```

**Review by dr-orlovsky — APPROVED** [review]

File: ffi/android/Dockerfile (hunk 2 above)
Comment (zoedberg) [reply ffi/android/Dockerfile]: I updated the docker base image, but to avoid the `E0554` error I had to run a `cargo update`.

after doing that, I've received this error on build:
```
#15 420.3    Compiling rgb_node v0.1.0 (https://github.com/LNP-BP/rgb-node?branch=master#4502981b)
#15 433.1 error[E0061]: this function takes 6 arguments but 7 arguments were supplied
#15 433.1    --> src/lib.rs:236:10
#15 433.1     |
#15 433.1 236 |         .transfer(
#15 433.1     |          ^^^^^^^^ expected 6 arguments
#15 433.1 237 |             data.inputs,
#15 433.1     |             -----------
#15 433.1 238 |             data.allocate,
#15 433.1     |             -------------
#15 433.1 239 |             data.invoice,
#15 433.1     |             ------------
#15 433.1 240 |             data.prototype_psbt,
#15 433.1     |             -------------------
#15 433.1 241 |             data.fee,
#15 433.1     |             --------
#15 433.1 242 |             data.consignment_file,
#15 433.1     |             ---------------------
#15 433.1 243 |             data.transaction_file,
#15 433.1     |             --------------------- supplied 7 arguments
#15 433.1 
#15 433.2 error: aborting due to previous error
```
so I've fixed transfer signature.

but then on build I've received this error:
```
#15 464.8   = note: /usr/bin/ld: cannot find -lsqlite3
#15 464.8           collect2: error: ld returned 1 exit status
#15 464.8           
#15 464.8 
#15 464.8 error: aborting due to previous error
#15 464.8 
#15 464.8 error: could not compile `rgb`.
```

I tried to add `libsqlite3-dev` to the docker image, but still receiving the error (a little different from before):
```
#15 484.0   = note: /root/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lsqlite3
#15 484.0           clang: error: linker command failed with exit code 1 (use -v to see invocation)
#15 484.0           
#15 484.0 
#15 484.0 error: aborting due to previous error; 2 warnings emitted
#15 484.0 
#15 484.0 error: could not compile `rgb`.
```

therefore I need to debug the situation a little bit more

Comment (zoedberg) [reply ffi/android/Dockerfile]: fixed by adding this to `Cargo.toml`:
```
[dependencies.libsqlite3-sys]
version = "0.9.1"
features = ["bundled"]
```

File: ffi/android/build_rust.sh (hunk 6 above)
Comment (zoedberg) [reply ffi/android/build_rust.sh:15]: does this apply also outside docker? because these paths are also needed for local build. so if the answer is no, I would keep it as it is

File: ffi/android/Dockerfile (hunk 7 above)
Comment (zoedberg) [reply ffi/android/Dockerfile]: done

File: ffi/android/build_rust.sh (hunk 6 above)
Comment (dr-orlovsky) [reply ffi/android/build_rust.sh:15]: Does not apply, the idea to have both to simplify life of docker users :)

File: ffi/android/README.md [hunk 8]
```diff
@@ -1,33 +1,38 @@
...
+# Android bindings
 
-* Install bash
-* Install rustup
-* Install Swig 4.0
-* Install cmake (used to build zmq)
+## Build
+
+In order to build Android bindings, from the project root follow the _Local_ or
+_In docker_ instructions.
```
Comment (dr-orlovsky) [inline ffi/android/README.md]: Do you know that you can reference MD headers by doing stuff like `[Local](#local)`

File: rust-lib/Cargo.toml [hunk 9]
```diff
@@ -21,13 +21,11 @@ serde = { version = "~1.0.111", features = ["derive"] }
 serde_with = "~1.5.0"
 serde_json = "~1.0.55"
```
Comment (dr-orlovsky) [inline rust-lib/Cargo.toml:23]: Also need change `rgb_node` to `rgb_node = "~0.1.0"` in the lines above

**Review by dr-orlovsky — CHANGES_REQUESTED** [review]
Perfect. Need to update rgb_node dependency on the released version (RGB) and one small Nit with Readme and seems we are done here.

File: ffi/android/Dockerfile (hunk 2 above)
Comment (dr-orlovsky) [reply ffi/android/Dockerfile]: Yeah, these issues were related to https://github.com/LNP-BP/rgb-sdk/issues/8

File: ffi/android/build_rust.sh (hunk 6 above)
Comment (zoedberg) [reply ffi/android/build_rust.sh:15]: I don't understand, life of docker users is already pretty simple (they have to run just 3 commands in order to do everything, and adding a `.env` file won't change that number), and thanks to this change also local users have an easier life (since now they don't have to write the config file for cargo, manually changing the `NDK_HOME`)

File: ffi/android/README.md (hunk 8 above)
Comment (zoedberg) [reply ffi/android/README.md]: Sure, I know it, I just didn't think about it, sorry, good hint ;) I will do it also on node js doc (when refactoring documentation of the whole project)

**Comment by zoedberg** [comment]
Since this PR was related to android bindings dockerization, I propose to leave it open for the moment, split commits that are related with #8 and use those commits for a new PR. After merging that, we can merge this PR (directly with the correct docker base image). This will allow us to have atomic working commits and a cleaner history. @dr-orlovsky do you agree?

**Comment by dr-orlovsky** [comment]
@zoedberg I do agree

**Review by dr-orlovsky — APPROVED** [review]
LGTM, will merge once we will have https://github.com/LNP-BP/rgb-sdk/pull/10 merged
